resource: google_artifact_registry_vpcsc_config
generation_type: mmv1
source_file: products/artifactregistry/VPCSCConfig.yaml
api_service_name: artifactregistry.googleapis.com
api_version: v1
api_resource_type_kind: VpcscConfig
fields:
    - field: location
      provider_only: true
    - api_field: name
    - api_field: vpcscPolicy
